# Site settings
title: Pwn2Win CTF
email: elt at ctf-br.org
description: > # this means to ignore newlines until "baseurl:"
  Pwn2Win CTF - An awesome and hardcore hacking competition!
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://ctf-br.org" # the base hostname & protocol for your site
twitter_username: pwn2win
github_username:  pwn2winctf
comments: false

# Build settings
markdown: kramdown

Navigation:
- title: Home
 url: /index.html
- title: Let's Play
 url: https://pwn2.win
- title: Rules
 url: /rules.md
 - title: Regras
 url: /regras.md

